version: '3.7'

services:

  # https://hub.docker.com/_/postgres
  playground-postgres:
    image: postgres:alpine
    container_name: playground-postgres-database
    networks:
      - playground-network
    restart: "no"
    environment:
      POSTGRES_DATABASE: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5434:5432"

networks:
  playground-network:
